// <auto-generated />
using System;
using HospitalClassLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HospitalAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220124181102_Shifts4")]
    partial class Shifts4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("AllergenPatient", b =>
                {
                    b.Property<int>("AllergensId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientsId")
                        .HasColumnType("integer");

                    b.HasKey("AllergensId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("AllergenPatient");
                });

            modelBuilder.Entity("HospitalClassLib.MedicalRecords.Model.Medication", b =>
                {
                    b.Property<long>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MedicineID");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            MedicineID = 1L,
                            Name = "Synthroid",
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSurveyed")
                        .HasColumnType("boolean");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 1,
                            StartTime = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(3672),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 6,
                            IsSurveyed = false,
                            PatientId = 1,
                            StartTime = new DateTime(2021, 12, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 6,
                            IsSurveyed = false,
                            PatientId = 1,
                            StartTime = new DateTime(2021, 12, 15, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 6,
                            IsSurveyed = false,
                            PatientId = 1,
                            StartTime = new DateTime(2021, 12, 15, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 1,
                            StartTime = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(5844),
                            State = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 1,
                            StartTime = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(5860),
                            State = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(5865),
                            State = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(5870),
                            State = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(5876),
                            State = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(5881),
                            State = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            DoctorId = 1,
                            IsSurveyed = false,
                            PatientId = 2,
                            StartTime = new DateTime(2022, 1, 1, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublishable")
                        .HasColumnType("boolean");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Tekst neki",
                            Date = new DateTime(2022, 1, 24, 19, 11, 1, 359, DateTimeKind.Local).AddTicks(5276),
                            IsAnonymous = false,
                            IsApproved = true,
                            IsPublishable = true,
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Drugi neki",
                            Date = new DateTime(2022, 1, 24, 19, 11, 1, 364, DateTimeKind.Local).AddTicks(1777),
                            IsAnonymous = false,
                            IsApproved = true,
                            IsPublishable = true,
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Guest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("Jmbg")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Lbo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodType = 0,
                            DateOfBirth = new DateTime(1999, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            Email = "pera.peric@gmail.com",
                            Guest = false,
                            IsActivated = true,
                            IsBanned = false,
                            Jmbg = "123456789",
                            LastName = "Peric",
                            Name = "Pera",
                            Password = "pera",
                            Phone = "054987332",
                            Token = "ABC123DEF4AAAAC12345",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 2,
                            BloodType = 0,
                            DateOfBirth = new DateTime(1999, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            Email = "pera2.peric@gmail.com",
                            Guest = false,
                            IsActivated = true,
                            IsBanned = false,
                            Jmbg = "213456789",
                            LastName = "Maric",
                            Name = "Mare",
                            Password = "maric",
                            Phone = "054987332",
                            Token = "ABC213DEF4AAAAC12345",
                            Username = "mare"
                        });
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Question", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id", "SurveyId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SurveyId = 1,
                            Category = 0,
                            Text = "How would you rate doctors professionalism?",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            SurveyId = 1,
                            Category = 0,
                            Text = "How would you rate doctors politeness?",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            SurveyId = 1,
                            Category = 0,
                            Text = "How would you rate doctors technicality?",
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            SurveyId = 1,
                            Category = 0,
                            Text = "How would you rate doctors skill?",
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            SurveyId = 1,
                            Category = 0,
                            Text = "How would you rate doctors knowledge?",
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            SurveyId = 1,
                            Category = 1,
                            Text = "How would you rate hospital environment?",
                            Value = 1
                        },
                        new
                        {
                            Id = 7,
                            SurveyId = 1,
                            Category = 1,
                            Text = "How would you rate hospital equipment?",
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            SurveyId = 1,
                            Category = 1,
                            Text = "How would you rate hospital hygiene?",
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            SurveyId = 1,
                            Category = 1,
                            Text = "How would you rate hospital prices?",
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            SurveyId = 1,
                            Category = 1,
                            Text = "How would you rate hospital waiting time?",
                            Value = 1
                        },
                        new
                        {
                            Id = 11,
                            SurveyId = 1,
                            Category = 2,
                            Text = "How would you rate medical staffs professionalism?",
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            SurveyId = 1,
                            Category = 2,
                            Text = "How would you rate medical staffs politeness?",
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            SurveyId = 1,
                            Category = 2,
                            Text = "How would you rate medical staffs technicality?",
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            SurveyId = 1,
                            Category = 2,
                            Text = "How would you rate medical staffs skill?",
                            Value = 1
                        },
                        new
                        {
                            Id = 15,
                            SurveyId = 1,
                            Category = 2,
                            Text = "How would you rate medical staffs knowledge?",
                            Value = 4
                        },
                        new
                        {
                            Id = 1,
                            SurveyId = 2,
                            Category = 0,
                            Text = "How would you rate doctors professionalism?",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            SurveyId = 2,
                            Category = 0,
                            Text = "How would you rate doctors politeness?",
                            Value = 3
                        },
                        new
                        {
                            Id = 3,
                            SurveyId = 2,
                            Category = 0,
                            Text = "How would you rate doctors technicality?",
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            SurveyId = 2,
                            Category = 0,
                            Text = "How would you rate doctors skill?",
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            SurveyId = 2,
                            Category = 0,
                            Text = "How would you rate doctors knowledge?",
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            SurveyId = 2,
                            Category = 1,
                            Text = "How would you rate hospital environment?",
                            Value = 1
                        },
                        new
                        {
                            Id = 7,
                            SurveyId = 2,
                            Category = 1,
                            Text = "How would you rate hospital equipment?",
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            SurveyId = 2,
                            Category = 1,
                            Text = "How would you rate hospital hygiene?",
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            SurveyId = 2,
                            Category = 1,
                            Text = "How would you rate hospital prices?",
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            SurveyId = 2,
                            Category = 1,
                            Text = "How would you rate hospital waiting time?",
                            Value = 1
                        },
                        new
                        {
                            Id = 11,
                            SurveyId = 2,
                            Category = 2,
                            Text = "How would you rate medical staffs professionalism?",
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            SurveyId = 2,
                            Category = 2,
                            Text = "How would you rate medical staffs politeness?",
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            SurveyId = 2,
                            Category = 2,
                            Text = "How would you rate medical staffs technicality?",
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            SurveyId = 2,
                            Category = 2,
                            Text = "How would you rate medical staffs skill?",
                            Value = 1
                        },
                        new
                        {
                            Id = 15,
                            SurveyId = 2,
                            Category = 2,
                            Text = "How would you rate medical staffs knowledge?",
                            Value = 5
                        });
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Prasina"
                        });
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Building", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<long>("DoctorShiftID")
                        .HasColumnType("bigint");

                    b.Property<int>("DoctorSpecialization")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Jmbg")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<long>("VacationID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorShiftID");

                    b.HasIndex("VacationID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorShiftID = 1L,
                            DoctorSpecialization = 0,
                            Jmbg = "123456799",
                            LastName = "Jovanovic",
                            Name = "Jovan",
                            Password = "jova",
                            Username = "jova",
                            VacationID = 1L
                        },
                        new
                        {
                            Id = 2,
                            DoctorShiftID = 1L,
                            DoctorSpecialization = 0,
                            Jmbg = "123756799",
                            LastName = "Ilic",
                            Name = "Milan",
                            Password = "mico",
                            Username = "mico",
                            VacationID = 2L
                        },
                        new
                        {
                            Id = 3,
                            DoctorShiftID = 2L,
                            DoctorSpecialization = 8,
                            Jmbg = "123756799",
                            LastName = "Markovic",
                            Name = "Stevan",
                            Password = "mico",
                            Username = "mico",
                            VacationID = 3L
                        },
                        new
                        {
                            Id = 4,
                            DoctorShiftID = 2L,
                            DoctorSpecialization = 9,
                            Jmbg = "123756799",
                            LastName = "Visnjic",
                            Name = "Nikola",
                            Password = "mico",
                            Username = "mico",
                            VacationID = 4L
                        },
                        new
                        {
                            Id = 5,
                            DoctorShiftID = 3L,
                            DoctorSpecialization = 9,
                            Jmbg = "123756799",
                            LastName = "Mitic",
                            Name = "Strahinja",
                            Password = "mico",
                            Username = "mico",
                            VacationID = 1L
                        },
                        new
                        {
                            Id = 6,
                            DoctorShiftID = 3L,
                            DoctorSpecialization = 2,
                            Jmbg = "123756799",
                            LastName = "Despotovic",
                            Name = "Goran",
                            Password = "mico",
                            Username = "mico",
                            VacationID = 3L
                        },
                        new
                        {
                            Id = 7,
                            DoctorShiftID = 1L,
                            DoctorSpecialization = 7,
                            Jmbg = "123756799",
                            LastName = "Njegos",
                            Name = "Milomir",
                            Password = "mico",
                            Username = "mico",
                            VacationID = 2L
                        });
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Equipment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("RoomID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("RoomID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Floor", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("BuildingID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BuildingID");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.MoveEquipment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<long?>("DestinationRoomID")
                        .HasColumnType("bigint");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<long?>("EquipmentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RelocationTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("DestinationRoomID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("MoveEquipments");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Receipt", b =>
                {
                    b.Property<long>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("MedicineName")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("ReceiptID");

                    b.ToTable("Receipts");

                    b.HasData(
                        new
                        {
                            ReceiptID = 1L,
                            Amount = 1,
                            Date = new DateTime(2022, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Diagnosis = "Korona",
                            DoctorId = 1,
                            MedicineName = "Synthroid",
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Room", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("FloorID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("FloorID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Shift", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ShiftEnd")
                        .HasColumnType("text");

                    b.Property<string>("ShiftStart")
                        .HasColumnType("text");

                    b.Property<string>("ShiftType")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Deleted = false,
                            ShiftEnd = "13:00",
                            ShiftStart = "7:00",
                            ShiftType = "Morning shift"
                        },
                        new
                        {
                            ID = 2L,
                            Deleted = false,
                            ShiftEnd = "20:00",
                            ShiftStart = "13:00",
                            ShiftType = "Afternoon shift"
                        },
                        new
                        {
                            ID = 3L,
                            Deleted = false,
                            ShiftEnd = "7:00",
                            ShiftStart = "20:00",
                            ShiftType = "Night shift"
                        });
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.VacationPeriod", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VacationDescription")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Vacations");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            EndTime = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VacationDescription = "Summer Vacation"
                        },
                        new
                        {
                            ID = 2L,
                            EndTime = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VacationDescription = "Winter Vacation"
                        },
                        new
                        {
                            ID = 3L,
                            EndTime = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VacationDescription = "Ski Trip"
                        },
                        new
                        {
                            ID = 4L,
                            EndTime = new DateTime(2022, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VacationDescription = "Summer Vacation"
                        });
                });

            modelBuilder.Entity("AllergenPatient", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalClassLib.Schedule.Model.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Appointment", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalClassLib.Schedule.Model.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Feedback", b =>
                {
                    b.HasOne("HospitalClassLib.Schedule.Model.Patient", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Patient", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Question", b =>
                {
                    b.HasOne("HospitalClassLib.Schedule.Model.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Survey", b =>
                {
                    b.HasOne("HospitalClassLib.Schedule.Model.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalClassLib.Schedule.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Doctor", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Shift", "DoctorShift")
                        .WithMany()
                        .HasForeignKey("DoctorShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalClassLib.SharedModel.VacationPeriod", "Vacation")
                        .WithMany()
                        .HasForeignKey("VacationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorShift");

                    b.Navigation("Vacation");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Equipment", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Floor", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingID");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.MoveEquipment", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Room", "DestinationRoom")
                        .WithMany()
                        .HasForeignKey("DestinationRoomID");

                    b.HasOne("HospitalClassLib.SharedModel.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID");

                    b.Navigation("DestinationRoom");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Room", b =>
                {
                    b.HasOne("HospitalClassLib.SharedModel.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorID");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HospitalClassLib.Schedule.Model.Survey", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("HospitalClassLib.SharedModel.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
